module.exports = {
    /*AUTH*/
    AUTH_TOKEN_FAILD: 'Failed to authenticate token.',
    AUTH_TOKEN_EMPTY: 'Your session has expired. Please login again to continue.',
    DATA_NOT_FOUND: 'Data not found.',
    DATA_FOUND: 'Data found.',
    SUCCESS: 'Successfully.',
    ACL_ERROR: 'Insufficient permissions to access resource',
    URL_EXPIRED: 'Url has been expired or may be invalid.',
    IS_OWN_ACL_ERROR: 'You don\'t have permission to change this record.',
    /*Common*/
    INTERNAL_ERROR: 'Internal error please try again.',
    EMAIL_NOT_SEND: 'Email not sent please try again',
    SERVICE_NOT_AVAILABLE: 'Sorry, service not yet available in your area.',
    INVALID_ZIP: 'Please enter a valid zipcode.',
    VERSION_UPDATE: 'App update required.',
    /*User Model*/
    EMAIL_SUCCESS: 'Email validated.',
    EMAIL_EXIST: 'An account already exists with this email address.',
    EMAIL_DOMAIN_NOT_EXIST: 'This user\'s email domain does not exist in your company domains list.',
    /*Users Controller*/
    TOKEN_REFRESH_SUCCESS: 'Token Successfully refresh.',
    DOMAIN_ASSOCIATED_WITH_OTHER_COMPANY: 'This user\'s email domain does not exist in your company domains list.', //ND-63 Author : Sanjay Pawar
    REQUEST_CODE_SUCCESS: 'Code successfully generated.',
    LOGIN_SUCCESS: 'Successfully login.',
    LOGOUT_SUCCESS: 'Successfully logout.',
    LOGIN_INVALID: 'Email & Password do not match.',
    LOGIN_DEACTIVE: 'Account is not active yet. Please contact the support team.',
    LOGIN_DEACTIVE_CORE: 'This account is not active. Please contact our support team at <a href="https://support.premiertalentpartners.com/support/tickets/new" target="_blank">https://support.premiertalentpartners.com/support/tickets/new</a>',
    LOGIN_DELETED: 'Account has been deactivated. Please contact the support team.',
    USER_NOT_EXIST: 'User does not exist.',
    EMAIL_NOT_EXIST: "The email you entered doesn't belong to an account.",
    REGISTER_SUCCESS: 'Registration successfully completed.',
    REGISTER_ERROR: 'Registration could not be completed.',
    REGISTER_SUCCESS_EMAIL_NOT_SEND: 'Registration successfully completed but email not send. Please contact the support team',
    PASSWORD_SENT: 'Password successfully sent to your email.',
    PASSWORD_LINK_SENT: 'You will receive an email with reset password instructions momentarily.',
    PROFILE_NOT_UPDATE: 'Profile could not be updated. Please try again later.',
    PROFILE_UPDATE: 'Profile successfully updated.',
    USER_INFO_UPDATE: 'User successfully updated.',
    USER_INFO_ERROR: 'User could not be updated.',
    USER_LOCKED: 'Locked successfully.',
    OLD_PASSWORD_INVALID: 'Old password is incorrect.',
    PASSWORD_CHANGE_ERROR: 'Password could not be changed.',
    PASSWORD_CHANGE_SUCCESS: 'Password successfully changed.',
    PROFILE_UPDATE_SUCCESS: 'Profile successfully updated.',
    INVALID_ACTIVATION_LINK: 'This activation link is expired or has already been used.',
    INVALID_RESET_PASSWORD_LINK: 'This reset password link is expired or have already been used.',
    PASSWORD_NOT_GENRATE: 'Your current password is missing or incorrect; it\'s required to change the Password',
    ACTIVATION_SUCCESS: 'Your account has been successfully activated.',
    ACCOUNT_NOT_ACTIVATED: 'You have not yet activated your account.',
    FAKE_EMAIL:
        'It looks like you\'re registering with a personal email account. Please create your account with your corporate email. For more help, please contact <strong>ajna-team@premiertalentpartners.com.</strong>',
    ADD_USER_DOMAIN_EMAIL_EXIST:
        '<p>Thank you for registering with Ajna! Your email domain belongs to an organization that already registered. We\'ve notified the Primary Admin User (see below) to add you as a user to the organization. Once your account is approved by this user, you will receive an email with the next steps.</p>',
    TRY_AGAIN: 'Try again.',
    NOT_SAVED: "Data could not be saved.",
    NOT_UPDATED: "Data could not be updated.",

    /*Feed Controller*/
    COMMENT_ADDED:"Comment added successfully",
    DISPLAY_COMMENT:"Comments successfully displayed ",
    DISPLAY_MSG:"Data display successfully",
};
